task: specify the default constructor as noexcept
Fixes build breakage introduced in d696757b139c0d8950e603f6eed775dd96022557, e.g.:
```
../../include/seastar/core/future-util.hh:353:86: error: use of deleted function ‘seastar::continuation_base<T>::continuation_base() [with T = {std::experimental::fundamentals_v1::optional<seastar::temporary_buffer<char> >}]’
  353 |     explicit repeat_until_value_state(AsyncAction action) : _action(std::move(action)) {}
      |                                                                                      ^
In file included from ../../src/core/reactor_backend.hh:24,
                 from ../../src/core/reactor_backend.cc:21:
../../include/seastar/core/future.hh:528:5: note: ‘seastar::continuation_base<T>::continuation_base() noexcept [with T = {std::experimental::fundamentals_v1::optional<seastar::temporary_buffer<char> >}]’ is implicitly deleted because its exception-specification does not match the implicit exception-specification ‘’
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>